language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

before_install:
  - npm install -g nightwatch
  - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar -O selenium.jar

after_script:
  - nightwatch -v
  - java -jar selenium.jar