[package]
name = "polaris"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies.iron]
version = "0.4.0"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies]
rustc-serialize = "0.3"

[dependencies]
router = "*"
mount  = "*"
staticfile = "*"

[dependencies]
toml = "0.2"