[package]
name = "polaris"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies]
id3 = { git = "https://github.com/jameshurst/rust-id3" }
iron = "0.4.0"
mount = "0.2.1"
oven = { git = "https://github.com/agersant/oven", branch = "remove_cookie_dep" } 
params = "0.3.1"
regex = "0.1"
router = "0.4.0"
rustc-serialize = "0.3"
staticfile = "0.3.0"
toml = "0.2"
url = "1.2.0"