[package]
name = "polaris"
version = "0.5.1"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[features]
ui = []

[dependencies]
ape = "0.1.2"
app_dirs = { git = "https://github.com/agersant/app-dirs-rs" }
diesel = { version = "0.13.0", features = ["sqlite"] }
diesel_codegen = { version = "0.13.0", features = ["sqlite"] }
error-chain = "0.10.0"
getopts = "0.2.14"
hyper = "0.10.0"
id3 = "0.1.11"
image = "0.13.0"
iron = "0.5.1"
lewton = "0.5.2"
metaflac = "0.1.4"
mount = "0.3.0"
params = "*"
rand = "0.3.15"
regex = "0.1"
ring = "0.9.7"
reqwest = "0.6.2"
router = "0.5.1"
secure-session = "0.1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
staticfile = "0.4.0"
toml = "=0.3.2"
typemap = "0.3"
url = "1.2.0"

[dependencies.rusqlite]
version = "0.11.0"
features = ["bundled"]

[target.'cfg(windows)'.dependencies]
winapi = { git = "https://github.com/retep998/winapi-rs", branch="0.2" }
kernel32-sys = { git = "https://github.com/retep998/winapi-rs", branch="0.2" }
shell32-sys = { git = "https://github.com/retep998/winapi-rs", branch="0.2" }
user32-sys = { git = "https://github.com/retep998/winapi-rs", branch="0.2" }
uuid = "0.5.0"

[target.'cfg(unix)'.dependencies]
unix-daemonize = "0.1.2"
