[package]
name = "polaris"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[features]
ui = []

[dependencies]
ape = "0.1.2"
getopts = "0.2.14"
hyper = "0.9.10"
id3 = { git = "https://github.com/jameshurst/rust-id3" }
image = "0.10.3"
iron = "0.4.0"
lewton = "0.4.0"
mount = "0.2.1"
ogg = "0.4.0"
oven = { git = "https://github.com/agersant/oven", branch = "remove_cookie_dep" } 
params = "0.3.1"
regex = "0.1"
router = "0.4.0"
rustc-serialize = "0.3"
sqlite = "0.23.0"
staticfile = "0.3.0"
toml = "0.2"
url = "1.2.0"

winapi = { git = "https://github.com/retep998/winapi-rs" }
kernel32-sys = { git = "https://github.com/retep998/winapi-rs" }
shell32-sys = { git = "https://github.com/retep998/winapi-rs" }
user32-sys = { git = "https://github.com/retep998/winapi-rs" }
uuid = { version = "0.3.0", features = ["v5"] }