[package]
name = "polaris"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies.iron]
version = "0.4.0"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies]
id3 = { git = "https://github.com/jameshurst/rust-id3" }
mount  = "*"
regex = "0.1"
router = "*"
rustc-serialize = "0.3"
staticfile = "*"
toml = "0.2"