[package]
name = "polaris"
version = "0.2.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[features]
ui = []

[dependencies]
ape = "0.1.2"
app_dirs = { git = "https://github.com/agersant/app-dirs-rs" }
getopts = "0.2.14"
hyper = "0.9.10"
id3 = "0.1.11"
image = "0.10.3"
iron = "0.4.0"
lewton = "0.4.1"
metaflac = "0.1.4"
mount = "0.2.1"
ogg = "0.4.0"
oven = { git = "https://github.com/agersant/oven", branch = "remove_cookie_dep" } 
params = "0.5.1"
regex = "0.1"
router = "0.4.0"
rustc-serialize = "0.3"
sqlite = "0.23.0"
staticfile = "0.3.0"
toml = "0.2"
url = "1.2.0"

winapi = "0.2.8"
kernel32-sys = "0.2.2"
shell32-sys = "0.1.1"
user32-sys = "0.2.0"
uuid = { version = "0.3.0", features = ["v5"] }