[package]
name = "polaris"
version = "0.11.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]
edition = "2018"

[features]
default = ["service-actix"]
ui = []
profile-index = ["flame", "flamer"]
service-actix = ["actix-files", "actix-http", "actix-rt", "actix-web"]
service-rocket = ["rocket", "rocket_contrib"]

[dependencies]
actix-files = { version = "0.2", optional = true }
actix-http = { version = "1.0", optional = true }
actix-web = { version = "2.0", optional = true }
actix-rt = { version = "1.0", optional = true }
anyhow = "1.0"
ape = "0.2.0"
app_dirs = "1.1.1"
base64 = "0.11.0"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "1.4", features = ["sqlite"] }
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4", optional = true }
getopts = "0.2.15"
id3 = "0.3"
image = "0.22"
libsqlite3-sys = { version = "0.16", features = ["bundled-windows"] }
rustfm-scrobble = "0.9.2"
lewton = "0.9.1"
log = "0.4.5"
metaflac = "0.2"
mp3-duration = "0.1"
pbkdf2 = "0.3"
rand = "0.7"
regex = "1.2"
reqwest = "0.9.2"
rocket = { version = "0.4.2", optional = true }
rust-crypto = "0.2.36"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
simplelog = "0.7"
thiserror = "1.0"
time = "0.1"
toml = "0.5"

[dependencies.rocket_contrib]
version = "0.4.2"
default_features = false
features = ["json", "serve"]
optional = true

[target.'cfg(windows)'.dependencies]
uuid = "0.8"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.3"
features = ["winuser", "libloaderapi", "shellapi", "errhandlingapi"]

[target.'cfg(unix)'.dependencies]
sd-notify = "0.1.0"
unix-daemonize = "0.1.2"
