[package]
name = "swine"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies.iron]
version = "0.4.0"

[dependencies]
router = "*"
staticfile = "*"
mount  = "*"