[package]
name = "polaris"
version = "0.8.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[features]
ui = []

[dependencies]
ape = "0.2.0"
app_dirs = "1.1.1"
base64 = "0.9.3"
diesel = { version = "1.3.3", features = ["sqlite"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
error-chain = "0.12.0"
getopts = "0.2.15"
hyper = "0.12.11"
id3 = "0.2.3"
image = "0.20.0"
iron = "0.6.0"
rustfm-scrobble = "0.9.1"
lewton = "0.9.1"
log = "0.4.5"
md5 = "0.5.0"
metaflac = "0.1.8"
mount = "0.4.0"
mp3-duration = "0.1.0"
params = { git = "https://github.com/agersant/params" }
rand = "0.5.5"
regex = "1.0.5"
ring = "0.13.2"
reqwest = "0.9.2"
rocket = "0.4.0-dev"
router = "0.6.0"
rust-crypto = "0.2.36"
secure-session = "0.3.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.2.1"
staticfile = "0.5.0"
simplelog = "0.5.2"
toml = "0.4.5"
typemap = "0.3"
url = "1.2.0"

[patch.crates-io.rocket]
git = "https://github.com/SergioBenitez/Rocket.git"
rev = "556206e"

[patch.crates-io.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
rev = "556206e"

[dependencies.rocket_contrib]
version = "0.4.0-dev"
default_features = false
features = ["json", "serve"]

[dependencies.rusqlite]
version = "0.14.0"
features = ["bundled"]

[target.'cfg(windows)'.dependencies]
uuid = "0.7.1"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.3"
features = ["winuser", "libloaderapi", "shellapi", "errhandlingapi"]

[target.'cfg(unix)'.dependencies]
unix-daemonize = "0.1.2"
