auth_secret = 'Something very secret'

album_art_pattern = '^Folder\.(png|jpg|jpeg)$'

[[mount_dirs]]
name = 'root'
source = 'M:/Music/Genres/'

[[users]]
name = 'agersant'
password = 'test'

[ydns]
host = 'your_hostname.ydns.eu'
username = 'your_username'
password = 'your_ydns_password'
