# Type anything here, don't leave the default
auth_secret = 'Something very secret'

# Pattern used to match album art matching a file
album_art_pattern = '^Folder\.(png|jpg|jpeg)$'

# Directories where your music is stored
[[mount_dirs]]
source = 'C:/Users/your_name/Music'		# Location of the directory on your computer
name = 'root'							# Public-facing name for this directory

# [[mount_dirs]]
# source = 'D:/more_music'
# name = 'extra'

# Users having access to the service
[[users]]
name = 'your_first_user'
password = 'your_first_password'		# Passwords are stored unencrypted. Do not re-use a sensitive password!

# Use this section if you want Polaris to broadcast your IP to https://ydns.io 
# [ydns]
# host = 'your_hostname.ydns.eu'
# username = 'your_username'
# password = 'your_ydns_password'
