name: Validate Pull Request
on: push

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/cargo@v1
      with:
        command: test
        toolchain: nightly
        args: --release --all-features
